-- Add address details and tax fields to properties table

ALTER TABLE properties
  ADD COLUMN IF NOT EXISTS address_number TEXT,
  ADD COLUMN IF NOT EXISTS address_complement TEXT,
  ADD COLUMN IF NOT EXISTS iptu NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS condo_fee NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gas_fee NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS water_fee NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS electricity_fee NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_fees NUMERIC(12,2) DEFAULT 0;
